package com.bgp.mgr.dao.domain;

import java.util.Date;

public class AssessInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.userContentId
     *
     * @mbggenerated
     */
    private String usercontentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.replyUserId
     *
     * @mbggenerated
     */
    private String replyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.userImage
     *
     * @mbggenerated
     */
    private String userimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.releaseTime
     *
     * @mbggenerated
     */
    private Date releasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.score
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.replyUserName
     *
     * @mbggenerated
     */
    private String replyusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.userContentTime
     *
     * @mbggenerated
     */
    private Date usercontenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.messageType
     *
     * @mbggenerated
     */
    private String messagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessInfo.likeNumber
     *
     * @mbggenerated
     */
    private String likenumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.id
     *
     * @return the value of assessInfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.id
     *
     * @param id the value for assessInfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.userContentId
     *
     * @return the value of assessInfo.userContentId
     *
     * @mbggenerated
     */
    public String getUsercontentid() {
        return usercontentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.userContentId
     *
     * @param usercontentid the value for assessInfo.userContentId
     *
     * @mbggenerated
     */
    public void setUsercontentid(String usercontentid) {
        this.usercontentid = usercontentid == null ? null : usercontentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.userId
     *
     * @return the value of assessInfo.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.userId
     *
     * @param userid the value for assessInfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.userName
     *
     * @return the value of assessInfo.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.userName
     *
     * @param username the value for assessInfo.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.replyUserId
     *
     * @return the value of assessInfo.replyUserId
     *
     * @mbggenerated
     */
    public String getReplyuserid() {
        return replyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.replyUserId
     *
     * @param replyuserid the value for assessInfo.replyUserId
     *
     * @mbggenerated
     */
    public void setReplyuserid(String replyuserid) {
        this.replyuserid = replyuserid == null ? null : replyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.userImage
     *
     * @return the value of assessInfo.userImage
     *
     * @mbggenerated
     */
    public String getUserimage() {
        return userimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.userImage
     *
     * @param userimage the value for assessInfo.userImage
     *
     * @mbggenerated
     */
    public void setUserimage(String userimage) {
        this.userimage = userimage == null ? null : userimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.releaseTime
     *
     * @return the value of assessInfo.releaseTime
     *
     * @mbggenerated
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.releaseTime
     *
     * @param releasetime the value for assessInfo.releaseTime
     *
     * @mbggenerated
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.content
     *
     * @return the value of assessInfo.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.content
     *
     * @param content the value for assessInfo.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.score
     *
     * @return the value of assessInfo.score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.score
     *
     * @param score the value for assessInfo.score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.replyUserName
     *
     * @return the value of assessInfo.replyUserName
     *
     * @mbggenerated
     */
    public String getReplyusername() {
        return replyusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.replyUserName
     *
     * @param replyusername the value for assessInfo.replyUserName
     *
     * @mbggenerated
     */
    public void setReplyusername(String replyusername) {
        this.replyusername = replyusername == null ? null : replyusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.userContentTime
     *
     * @return the value of assessInfo.userContentTime
     *
     * @mbggenerated
     */
    public Date getUsercontenttime() {
        return usercontenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.userContentTime
     *
     * @param usercontenttime the value for assessInfo.userContentTime
     *
     * @mbggenerated
     */
    public void setUsercontenttime(Date usercontenttime) {
        this.usercontenttime = usercontenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.type
     *
     * @return the value of assessInfo.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.type
     *
     * @param type the value for assessInfo.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.messageType
     *
     * @return the value of assessInfo.messageType
     *
     * @mbggenerated
     */
    public String getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.messageType
     *
     * @param messagetype the value for assessInfo.messageType
     *
     * @mbggenerated
     */
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype == null ? null : messagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessInfo.likeNumber
     *
     * @return the value of assessInfo.likeNumber
     *
     * @mbggenerated
     */
    public String getLikenumber() {
        return likenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessInfo.likeNumber
     *
     * @param likenumber the value for assessInfo.likeNumber
     *
     * @mbggenerated
     */
    public void setLikenumber(String likenumber) {
        this.likenumber = likenumber == null ? null : likenumber.trim();
    }
}