package com.bgp.mgr.dao.domain;

public class FileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.userId
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.friendsCircleId
     *
     * @mbggenerated
     */
    private Long friendsCircleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.gameId
     *
     * @mbggenerated
     */
    private Long gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.recordId
     *
     * @mbggenerated
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.fileName
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.fileAddress
     *
     * @mbggenerated
     */
    private String fileAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.fileType
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileInfo.fileUseType
     *
     * @mbggenerated
     */
    private String fileUseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.id
     *
     * @return the value of fileInfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.id
     *
     * @param id the value for fileInfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.userId
     *
     * @return the value of fileInfo.userId
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.userId
     *
     * @param userId the value for fileInfo.userId
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.friendsCircleId
     *
     * @return the value of fileInfo.friendsCircleId
     *
     * @mbggenerated
     */
    public Long getFriendsCircleId() {
        return friendsCircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.friendsCircleId
     *
     * @param friendsCircleId the value for fileInfo.friendsCircleId
     *
     * @mbggenerated
     */
    public void setFriendsCircleId(Long friendsCircleId) {
        this.friendsCircleId = friendsCircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.gameId
     *
     * @return the value of fileInfo.gameId
     *
     * @mbggenerated
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.gameId
     *
     * @param gameId the value for fileInfo.gameId
     *
     * @mbggenerated
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.recordId
     *
     * @return the value of fileInfo.recordId
     *
     * @mbggenerated
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.recordId
     *
     * @param recordId the value for fileInfo.recordId
     *
     * @mbggenerated
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.fileName
     *
     * @return the value of fileInfo.fileName
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.fileName
     *
     * @param fileName the value for fileInfo.fileName
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.fileAddress
     *
     * @return the value of fileInfo.fileAddress
     *
     * @mbggenerated
     */
    public String getFileAddress() {
        return fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.fileAddress
     *
     * @param fileAddress the value for fileInfo.fileAddress
     *
     * @mbggenerated
     */
    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress == null ? null : fileAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.type
     *
     * @return the value of fileInfo.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.type
     *
     * @param type the value for fileInfo.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.fileType
     *
     * @return the value of fileInfo.fileType
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.fileType
     *
     * @param fileType the value for fileInfo.fileType
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileInfo.fileUseType
     *
     * @return the value of fileInfo.fileUseType
     *
     * @mbggenerated
     */
    public String getFileUseType() {
        return fileUseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileInfo.fileUseType
     *
     * @param fileUseType the value for fileInfo.fileUseType
     *
     * @mbggenerated
     */
    public void setFileUseType(String fileUseType) {
        this.fileUseType = fileUseType == null ? null : fileUseType.trim();
    }
}