package com.bgp.mgr.dao.domain;

import java.util.Date;

public class FriendsCircleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.userId
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.record
     *
     * @mbggenerated
     */
    private String record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.likeNumber
     *
     * @mbggenerated
     */
    private String likeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.ranking
     *
     * @mbggenerated
     */
    private String ranking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.score
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.gameWin
     *
     * @mbggenerated
     */
    private String gameWin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.gameRating
     *
     * @mbggenerated
     */
    private String gameRating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.created_date
     *
     * @mbggenerated
     */
    private Date created_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.id
     *
     * @return the value of friendsCircleInfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.id
     *
     * @param id the value for friendsCircleInfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.userId
     *
     * @return the value of friendsCircleInfo.userId
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.userId
     *
     * @param userId the value for friendsCircleInfo.userId
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.content
     *
     * @return the value of friendsCircleInfo.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.content
     *
     * @param content the value for friendsCircleInfo.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.record
     *
     * @return the value of friendsCircleInfo.record
     *
     * @mbggenerated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.record
     *
     * @param record the value for friendsCircleInfo.record
     *
     * @mbggenerated
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.likeNumber
     *
     * @return the value of friendsCircleInfo.likeNumber
     *
     * @mbggenerated
     */
    public String getLikeNumber() {
        return likeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.likeNumber
     *
     * @param likeNumber the value for friendsCircleInfo.likeNumber
     *
     * @mbggenerated
     */
    public void setLikeNumber(String likeNumber) {
        this.likeNumber = likeNumber == null ? null : likeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.ranking
     *
     * @return the value of friendsCircleInfo.ranking
     *
     * @mbggenerated
     */
    public String getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.ranking
     *
     * @param ranking the value for friendsCircleInfo.ranking
     *
     * @mbggenerated
     */
    public void setRanking(String ranking) {
        this.ranking = ranking == null ? null : ranking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.score
     *
     * @return the value of friendsCircleInfo.score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.score
     *
     * @param score the value for friendsCircleInfo.score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.gameWin
     *
     * @return the value of friendsCircleInfo.gameWin
     *
     * @mbggenerated
     */
    public String getGameWin() {
        return gameWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.gameWin
     *
     * @param gameWin the value for friendsCircleInfo.gameWin
     *
     * @mbggenerated
     */
    public void setGameWin(String gameWin) {
        this.gameWin = gameWin == null ? null : gameWin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.gameRating
     *
     * @return the value of friendsCircleInfo.gameRating
     *
     * @mbggenerated
     */
    public String getGameRating() {
        return gameRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.gameRating
     *
     * @param gameRating the value for friendsCircleInfo.gameRating
     *
     * @mbggenerated
     */
    public void setGameRating(String gameRating) {
        this.gameRating = gameRating == null ? null : gameRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.type
     *
     * @return the value of friendsCircleInfo.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.type
     *
     * @param type the value for friendsCircleInfo.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.created_date
     *
     * @return the value of friendsCircleInfo.created_date
     *
     * @mbggenerated
     */
    public Date getCreated_date() {
        return created_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.created_date
     *
     * @param created_date the value for friendsCircleInfo.created_date
     *
     * @mbggenerated
     */
    public void setCreated_date(Date created_date) {
        this.created_date = created_date;
    }
}