package com.bgp.mgr.dao.domain;

import java.util.Date;

public class FriendsCircleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.userContent
     *
     * @mbggenerated
     */
    private String usercontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.record
     *
     * @mbggenerated
     */
    private String record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.likeNumber
     *
     * @mbggenerated
     */
    private String likenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.ranking
     *
     * @mbggenerated
     */
    private String ranking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.score
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.gameWin
     *
     * @mbggenerated
     */
    private String gamewin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.gameRating
     *
     * @mbggenerated
     */
    private String gamerating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendsCircleInfo.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.id
     *
     * @return the value of friendsCircleInfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.id
     *
     * @param id the value for friendsCircleInfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.userId
     *
     * @return the value of friendsCircleInfo.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.userId
     *
     * @param userid the value for friendsCircleInfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.userContent
     *
     * @return the value of friendsCircleInfo.userContent
     *
     * @mbggenerated
     */
    public String getUsercontent() {
        return usercontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.userContent
     *
     * @param usercontent the value for friendsCircleInfo.userContent
     *
     * @mbggenerated
     */
    public void setUsercontent(String usercontent) {
        this.usercontent = usercontent == null ? null : usercontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.record
     *
     * @return the value of friendsCircleInfo.record
     *
     * @mbggenerated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.record
     *
     * @param record the value for friendsCircleInfo.record
     *
     * @mbggenerated
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.likeNumber
     *
     * @return the value of friendsCircleInfo.likeNumber
     *
     * @mbggenerated
     */
    public String getLikenumber() {
        return likenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.likeNumber
     *
     * @param likenumber the value for friendsCircleInfo.likeNumber
     *
     * @mbggenerated
     */
    public void setLikenumber(String likenumber) {
        this.likenumber = likenumber == null ? null : likenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.ranking
     *
     * @return the value of friendsCircleInfo.ranking
     *
     * @mbggenerated
     */
    public String getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.ranking
     *
     * @param ranking the value for friendsCircleInfo.ranking
     *
     * @mbggenerated
     */
    public void setRanking(String ranking) {
        this.ranking = ranking == null ? null : ranking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.score
     *
     * @return the value of friendsCircleInfo.score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.score
     *
     * @param score the value for friendsCircleInfo.score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.gameWin
     *
     * @return the value of friendsCircleInfo.gameWin
     *
     * @mbggenerated
     */
    public String getGamewin() {
        return gamewin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.gameWin
     *
     * @param gamewin the value for friendsCircleInfo.gameWin
     *
     * @mbggenerated
     */
    public void setGamewin(String gamewin) {
        this.gamewin = gamewin == null ? null : gamewin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.gameRating
     *
     * @return the value of friendsCircleInfo.gameRating
     *
     * @mbggenerated
     */
    public String getGamerating() {
        return gamerating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.gameRating
     *
     * @param gamerating the value for friendsCircleInfo.gameRating
     *
     * @mbggenerated
     */
    public void setGamerating(String gamerating) {
        this.gamerating = gamerating == null ? null : gamerating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.type
     *
     * @return the value of friendsCircleInfo.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.type
     *
     * @param type the value for friendsCircleInfo.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendsCircleInfo.created_date
     *
     * @return the value of friendsCircleInfo.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendsCircleInfo.created_date
     *
     * @param createdDate the value for friendsCircleInfo.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}