package com.bgp.mgr.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected Integer limitSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public GameInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart = limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Integer getLimitSize() {
        return limitSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameNameIsNull() {
            addCriterion("gameName is null");
            return (Criteria) this;
        }

        public Criteria andGameNameIsNotNull() {
            addCriterion("gameName is not null");
            return (Criteria) this;
        }

        public Criteria andGameNameEqualTo(String value) {
            addCriterion("gameName =", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotEqualTo(String value) {
            addCriterion("gameName <>", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameGreaterThan(String value) {
            addCriterion("gameName >", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameGreaterThanOrEqualTo(String value) {
            addCriterion("gameName >=", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLessThan(String value) {
            addCriterion("gameName <", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLessThanOrEqualTo(String value) {
            addCriterion("gameName <=", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLike(String value) {
            addCriterion("gameName like", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotLike(String value) {
            addCriterion("gameName not like", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameIn(List<String> values) {
            addCriterion("gameName in", values, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotIn(List<String> values) {
            addCriterion("gameName not in", values, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameBetween(String value1, String value2) {
            addCriterion("gameName between", value1, value2, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotBetween(String value1, String value2) {
            addCriterion("gameName not between", value1, value2, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameIsNull() {
            addCriterion("gameEnName is null");
            return (Criteria) this;
        }

        public Criteria andGameEnNameIsNotNull() {
            addCriterion("gameEnName is not null");
            return (Criteria) this;
        }

        public Criteria andGameEnNameEqualTo(String value) {
            addCriterion("gameEnName =", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameNotEqualTo(String value) {
            addCriterion("gameEnName <>", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameGreaterThan(String value) {
            addCriterion("gameEnName >", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameGreaterThanOrEqualTo(String value) {
            addCriterion("gameEnName >=", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameLessThan(String value) {
            addCriterion("gameEnName <", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameLessThanOrEqualTo(String value) {
            addCriterion("gameEnName <=", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameLike(String value) {
            addCriterion("gameEnName like", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameNotLike(String value) {
            addCriterion("gameEnName not like", value, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameIn(List<String> values) {
            addCriterion("gameEnName in", values, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameNotIn(List<String> values) {
            addCriterion("gameEnName not in", values, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameBetween(String value1, String value2) {
            addCriterion("gameEnName between", value1, value2, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andGameEnNameNotBetween(String value1, String value2) {
            addCriterion("gameEnName not between", value1, value2, "gameEnName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLabelIsNull() {
            addCriterion("label is null");
            return (Criteria) this;
        }

        public Criteria andLabelIsNotNull() {
            addCriterion("label is not null");
            return (Criteria) this;
        }

        public Criteria andLabelEqualTo(String value) {
            addCriterion("label =", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotEqualTo(String value) {
            addCriterion("label <>", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThan(String value) {
            addCriterion("label >", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThanOrEqualTo(String value) {
            addCriterion("label >=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThan(String value) {
            addCriterion("label <", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThanOrEqualTo(String value) {
            addCriterion("label <=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLike(String value) {
            addCriterion("label like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotLike(String value) {
            addCriterion("label not like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelIn(List<String> values) {
            addCriterion("label in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotIn(List<String> values) {
            addCriterion("label not in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelBetween(String value1, String value2) {
            addCriterion("label between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotBetween(String value1, String value2) {
            addCriterion("label not between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andGameImageIsNull() {
            addCriterion("gameImage is null");
            return (Criteria) this;
        }

        public Criteria andGameImageIsNotNull() {
            addCriterion("gameImage is not null");
            return (Criteria) this;
        }

        public Criteria andGameImageEqualTo(String value) {
            addCriterion("gameImage =", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotEqualTo(String value) {
            addCriterion("gameImage <>", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageGreaterThan(String value) {
            addCriterion("gameImage >", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageGreaterThanOrEqualTo(String value) {
            addCriterion("gameImage >=", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageLessThan(String value) {
            addCriterion("gameImage <", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageLessThanOrEqualTo(String value) {
            addCriterion("gameImage <=", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageLike(String value) {
            addCriterion("gameImage like", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotLike(String value) {
            addCriterion("gameImage not like", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageIn(List<String> values) {
            addCriterion("gameImage in", values, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotIn(List<String> values) {
            addCriterion("gameImage not in", values, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageBetween(String value1, String value2) {
            addCriterion("gameImage between", value1, value2, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotBetween(String value1, String value2) {
            addCriterion("gameImage not between", value1, value2, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionIsNull() {
            addCriterion("gameIntroduction is null");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionIsNotNull() {
            addCriterion("gameIntroduction is not null");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionEqualTo(String value) {
            addCriterion("gameIntroduction =", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotEqualTo(String value) {
            addCriterion("gameIntroduction <>", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionGreaterThan(String value) {
            addCriterion("gameIntroduction >", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("gameIntroduction >=", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionLessThan(String value) {
            addCriterion("gameIntroduction <", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionLessThanOrEqualTo(String value) {
            addCriterion("gameIntroduction <=", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionLike(String value) {
            addCriterion("gameIntroduction like", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotLike(String value) {
            addCriterion("gameIntroduction not like", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionIn(List<String> values) {
            addCriterion("gameIntroduction in", values, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotIn(List<String> values) {
            addCriterion("gameIntroduction not in", values, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionBetween(String value1, String value2) {
            addCriterion("gameIntroduction between", value1, value2, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotBetween(String value1, String value2) {
            addCriterion("gameIntroduction not between", value1, value2, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionIsNull() {
            addCriterion("gameEnIntroduction is null");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionIsNotNull() {
            addCriterion("gameEnIntroduction is not null");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionEqualTo(String value) {
            addCriterion("gameEnIntroduction =", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionNotEqualTo(String value) {
            addCriterion("gameEnIntroduction <>", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionGreaterThan(String value) {
            addCriterion("gameEnIntroduction >", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("gameEnIntroduction >=", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionLessThan(String value) {
            addCriterion("gameEnIntroduction <", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionLessThanOrEqualTo(String value) {
            addCriterion("gameEnIntroduction <=", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionLike(String value) {
            addCriterion("gameEnIntroduction like", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionNotLike(String value) {
            addCriterion("gameEnIntroduction not like", value, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionIn(List<String> values) {
            addCriterion("gameEnIntroduction in", values, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionNotIn(List<String> values) {
            addCriterion("gameEnIntroduction not in", values, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionBetween(String value1, String value2) {
            addCriterion("gameEnIntroduction between", value1, value2, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameEnIntroductionNotBetween(String value1, String value2) {
            addCriterion("gameEnIntroduction not between", value1, value2, "gameEnIntroduction");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andMechanismIsNull() {
            addCriterion("mechanism is null");
            return (Criteria) this;
        }

        public Criteria andMechanismIsNotNull() {
            addCriterion("mechanism is not null");
            return (Criteria) this;
        }

        public Criteria andMechanismEqualTo(String value) {
            addCriterion("mechanism =", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismNotEqualTo(String value) {
            addCriterion("mechanism <>", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismGreaterThan(String value) {
            addCriterion("mechanism >", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismGreaterThanOrEqualTo(String value) {
            addCriterion("mechanism >=", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismLessThan(String value) {
            addCriterion("mechanism <", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismLessThanOrEqualTo(String value) {
            addCriterion("mechanism <=", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismLike(String value) {
            addCriterion("mechanism like", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismNotLike(String value) {
            addCriterion("mechanism not like", value, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismIn(List<String> values) {
            addCriterion("mechanism in", values, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismNotIn(List<String> values) {
            addCriterion("mechanism not in", values, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismBetween(String value1, String value2) {
            addCriterion("mechanism between", value1, value2, "mechanism");
            return (Criteria) this;
        }

        public Criteria andMechanismNotBetween(String value1, String value2) {
            addCriterion("mechanism not between", value1, value2, "mechanism");
            return (Criteria) this;
        }

        public Criteria andSevereIsNull() {
            addCriterion("severe is null");
            return (Criteria) this;
        }

        public Criteria andSevereIsNotNull() {
            addCriterion("severe is not null");
            return (Criteria) this;
        }

        public Criteria andSevereEqualTo(String value) {
            addCriterion("severe =", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotEqualTo(String value) {
            addCriterion("severe <>", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereGreaterThan(String value) {
            addCriterion("severe >", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereGreaterThanOrEqualTo(String value) {
            addCriterion("severe >=", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereLessThan(String value) {
            addCriterion("severe <", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereLessThanOrEqualTo(String value) {
            addCriterion("severe <=", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereLike(String value) {
            addCriterion("severe like", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotLike(String value) {
            addCriterion("severe not like", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereIn(List<String> values) {
            addCriterion("severe in", values, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotIn(List<String> values) {
            addCriterion("severe not in", values, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereBetween(String value1, String value2) {
            addCriterion("severe between", value1, value2, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotBetween(String value1, String value2) {
            addCriterion("severe not between", value1, value2, "severe");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(String value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(String value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(String value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(String value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(String value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(String value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLike(String value) {
            addCriterion("duration like", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotLike(String value) {
            addCriterion("duration not like", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<String> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<String> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(String value1, String value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(String value1, String value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(String value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(String value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(String value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(String value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(String value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(String value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLike(String value) {
            addCriterion("age like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotLike(String value) {
            addCriterion("age not like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<String> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<String> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(String value1, String value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(String value1, String value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinIsNull() {
            addCriterion("playerNumMin is null");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinIsNotNull() {
            addCriterion("playerNumMin is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinEqualTo(Integer value) {
            addCriterion("playerNumMin =", value, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinNotEqualTo(Integer value) {
            addCriterion("playerNumMin <>", value, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinGreaterThan(Integer value) {
            addCriterion("playerNumMin >", value, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("playerNumMin >=", value, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinLessThan(Integer value) {
            addCriterion("playerNumMin <", value, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinLessThanOrEqualTo(Integer value) {
            addCriterion("playerNumMin <=", value, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinIn(List<Integer> values) {
            addCriterion("playerNumMin in", values, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinNotIn(List<Integer> values) {
            addCriterion("playerNumMin not in", values, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinBetween(Integer value1, Integer value2) {
            addCriterion("playerNumMin between", value1, value2, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMinNotBetween(Integer value1, Integer value2) {
            addCriterion("playerNumMin not between", value1, value2, "playerNumMin");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxIsNull() {
            addCriterion("playerNumMax is null");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxIsNotNull() {
            addCriterion("playerNumMax is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxEqualTo(Integer value) {
            addCriterion("playerNumMax =", value, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxNotEqualTo(Integer value) {
            addCriterion("playerNumMax <>", value, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxGreaterThan(Integer value) {
            addCriterion("playerNumMax >", value, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("playerNumMax >=", value, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxLessThan(Integer value) {
            addCriterion("playerNumMax <", value, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxLessThanOrEqualTo(Integer value) {
            addCriterion("playerNumMax <=", value, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxIn(List<Integer> values) {
            addCriterion("playerNumMax in", values, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxNotIn(List<Integer> values) {
            addCriterion("playerNumMax not in", values, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxBetween(Integer value1, Integer value2) {
            addCriterion("playerNumMax between", value1, value2, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPlayerNumMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("playerNumMax not between", value1, value2, "playerNumMax");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedIsNull() {
            addCriterion("palyerNumSuggested is null");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedIsNotNull() {
            addCriterion("palyerNumSuggested is not null");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedEqualTo(Integer value) {
            addCriterion("palyerNumSuggested =", value, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedNotEqualTo(Integer value) {
            addCriterion("palyerNumSuggested <>", value, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedGreaterThan(Integer value) {
            addCriterion("palyerNumSuggested >", value, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedGreaterThanOrEqualTo(Integer value) {
            addCriterion("palyerNumSuggested >=", value, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedLessThan(Integer value) {
            addCriterion("palyerNumSuggested <", value, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedLessThanOrEqualTo(Integer value) {
            addCriterion("palyerNumSuggested <=", value, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedIn(List<Integer> values) {
            addCriterion("palyerNumSuggested in", values, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedNotIn(List<Integer> values) {
            addCriterion("palyerNumSuggested not in", values, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedBetween(Integer value1, Integer value2) {
            addCriterion("palyerNumSuggested between", value1, value2, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andPalyerNumSuggestedNotBetween(Integer value1, Integer value2) {
            addCriterion("palyerNumSuggested not between", value1, value2, "palyerNumSuggested");
            return (Criteria) this;
        }

        public Criteria andIsEntityIsNull() {
            addCriterion("isEntity is null");
            return (Criteria) this;
        }

        public Criteria andIsEntityIsNotNull() {
            addCriterion("isEntity is not null");
            return (Criteria) this;
        }

        public Criteria andIsEntityEqualTo(Integer value) {
            addCriterion("isEntity =", value, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityNotEqualTo(Integer value) {
            addCriterion("isEntity <>", value, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityGreaterThan(Integer value) {
            addCriterion("isEntity >", value, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityGreaterThanOrEqualTo(Integer value) {
            addCriterion("isEntity >=", value, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityLessThan(Integer value) {
            addCriterion("isEntity <", value, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityLessThanOrEqualTo(Integer value) {
            addCriterion("isEntity <=", value, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityIn(List<Integer> values) {
            addCriterion("isEntity in", values, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityNotIn(List<Integer> values) {
            addCriterion("isEntity not in", values, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityBetween(Integer value1, Integer value2) {
            addCriterion("isEntity between", value1, value2, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsEntityNotBetween(Integer value1, Integer value2) {
            addCriterion("isEntity not between", value1, value2, "isEntity");
            return (Criteria) this;
        }

        public Criteria andIsDlcIsNull() {
            addCriterion("isDlc is null");
            return (Criteria) this;
        }

        public Criteria andIsDlcIsNotNull() {
            addCriterion("isDlc is not null");
            return (Criteria) this;
        }

        public Criteria andIsDlcEqualTo(Integer value) {
            addCriterion("isDlc =", value, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcNotEqualTo(Integer value) {
            addCriterion("isDlc <>", value, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcGreaterThan(Integer value) {
            addCriterion("isDlc >", value, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDlc >=", value, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcLessThan(Integer value) {
            addCriterion("isDlc <", value, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcLessThanOrEqualTo(Integer value) {
            addCriterion("isDlc <=", value, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcIn(List<Integer> values) {
            addCriterion("isDlc in", values, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcNotIn(List<Integer> values) {
            addCriterion("isDlc not in", values, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcBetween(Integer value1, Integer value2) {
            addCriterion("isDlc between", value1, value2, "isDlc");
            return (Criteria) this;
        }

        public Criteria andIsDlcNotBetween(Integer value1, Integer value2) {
            addCriterion("isDlc not between", value1, value2, "isDlc");
            return (Criteria) this;
        }

        public Criteria andDesignerIsNull() {
            addCriterion("designer is null");
            return (Criteria) this;
        }

        public Criteria andDesignerIsNotNull() {
            addCriterion("designer is not null");
            return (Criteria) this;
        }

        public Criteria andDesignerEqualTo(String value) {
            addCriterion("designer =", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotEqualTo(String value) {
            addCriterion("designer <>", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerGreaterThan(String value) {
            addCriterion("designer >", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerGreaterThanOrEqualTo(String value) {
            addCriterion("designer >=", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLessThan(String value) {
            addCriterion("designer <", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLessThanOrEqualTo(String value) {
            addCriterion("designer <=", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLike(String value) {
            addCriterion("designer like", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotLike(String value) {
            addCriterion("designer not like", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerIn(List<String> values) {
            addCriterion("designer in", values, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotIn(List<String> values) {
            addCriterion("designer not in", values, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerBetween(String value1, String value2) {
            addCriterion("designer between", value1, value2, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotBetween(String value1, String value2) {
            addCriterion("designer not between", value1, value2, "designer");
            return (Criteria) this;
        }

        public Criteria andArtistIsNull() {
            addCriterion("artist is null");
            return (Criteria) this;
        }

        public Criteria andArtistIsNotNull() {
            addCriterion("artist is not null");
            return (Criteria) this;
        }

        public Criteria andArtistEqualTo(String value) {
            addCriterion("artist =", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotEqualTo(String value) {
            addCriterion("artist <>", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistGreaterThan(String value) {
            addCriterion("artist >", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistGreaterThanOrEqualTo(String value) {
            addCriterion("artist >=", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistLessThan(String value) {
            addCriterion("artist <", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistLessThanOrEqualTo(String value) {
            addCriterion("artist <=", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistLike(String value) {
            addCriterion("artist like", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotLike(String value) {
            addCriterion("artist not like", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistIn(List<String> values) {
            addCriterion("artist in", values, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotIn(List<String> values) {
            addCriterion("artist not in", values, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistBetween(String value1, String value2) {
            addCriterion("artist between", value1, value2, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotBetween(String value1, String value2) {
            addCriterion("artist not between", value1, value2, "artist");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNull() {
            addCriterion("publisher is null");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNotNull() {
            addCriterion("publisher is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherEqualTo(String value) {
            addCriterion("publisher =", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotEqualTo(String value) {
            addCriterion("publisher <>", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThan(String value) {
            addCriterion("publisher >", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("publisher >=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThan(String value) {
            addCriterion("publisher <", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThanOrEqualTo(String value) {
            addCriterion("publisher <=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLike(String value) {
            addCriterion("publisher like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotLike(String value) {
            addCriterion("publisher not like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherIn(List<String> values) {
            addCriterion("publisher in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotIn(List<String> values) {
            addCriterion("publisher not in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherBetween(String value1, String value2) {
            addCriterion("publisher between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotBetween(String value1, String value2) {
            addCriterion("publisher not between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublishYearIsNull() {
            addCriterion("publishYear is null");
            return (Criteria) this;
        }

        public Criteria andPublishYearIsNotNull() {
            addCriterion("publishYear is not null");
            return (Criteria) this;
        }

        public Criteria andPublishYearEqualTo(String value) {
            addCriterion("publishYear =", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearNotEqualTo(String value) {
            addCriterion("publishYear <>", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearGreaterThan(String value) {
            addCriterion("publishYear >", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearGreaterThanOrEqualTo(String value) {
            addCriterion("publishYear >=", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearLessThan(String value) {
            addCriterion("publishYear <", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearLessThanOrEqualTo(String value) {
            addCriterion("publishYear <=", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearLike(String value) {
            addCriterion("publishYear like", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearNotLike(String value) {
            addCriterion("publishYear not like", value, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearIn(List<String> values) {
            addCriterion("publishYear in", values, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearNotIn(List<String> values) {
            addCriterion("publishYear not in", values, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearBetween(String value1, String value2) {
            addCriterion("publishYear between", value1, value2, "publishYear");
            return (Criteria) this;
        }

        public Criteria andPublishYearNotBetween(String value1, String value2) {
            addCriterion("publishYear not between", value1, value2, "publishYear");
            return (Criteria) this;
        }

        public Criteria andHasChineseIsNull() {
            addCriterion("hasChinese is null");
            return (Criteria) this;
        }

        public Criteria andHasChineseIsNotNull() {
            addCriterion("hasChinese is not null");
            return (Criteria) this;
        }

        public Criteria andHasChineseEqualTo(Integer value) {
            addCriterion("hasChinese =", value, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseNotEqualTo(Integer value) {
            addCriterion("hasChinese <>", value, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseGreaterThan(Integer value) {
            addCriterion("hasChinese >", value, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseGreaterThanOrEqualTo(Integer value) {
            addCriterion("hasChinese >=", value, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseLessThan(Integer value) {
            addCriterion("hasChinese <", value, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseLessThanOrEqualTo(Integer value) {
            addCriterion("hasChinese <=", value, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseIn(List<Integer> values) {
            addCriterion("hasChinese in", values, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseNotIn(List<Integer> values) {
            addCriterion("hasChinese not in", values, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseBetween(Integer value1, Integer value2) {
            addCriterion("hasChinese between", value1, value2, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andHasChineseNotBetween(Integer value1, Integer value2) {
            addCriterion("hasChinese not between", value1, value2, "hasChinese");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherIsNull() {
            addCriterion("chinesePublisher is null");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherIsNotNull() {
            addCriterion("chinesePublisher is not null");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherEqualTo(String value) {
            addCriterion("chinesePublisher =", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotEqualTo(String value) {
            addCriterion("chinesePublisher <>", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherGreaterThan(String value) {
            addCriterion("chinesePublisher >", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherGreaterThanOrEqualTo(String value) {
            addCriterion("chinesePublisher >=", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherLessThan(String value) {
            addCriterion("chinesePublisher <", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherLessThanOrEqualTo(String value) {
            addCriterion("chinesePublisher <=", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherLike(String value) {
            addCriterion("chinesePublisher like", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotLike(String value) {
            addCriterion("chinesePublisher not like", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherIn(List<String> values) {
            addCriterion("chinesePublisher in", values, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotIn(List<String> values) {
            addCriterion("chinesePublisher not in", values, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherBetween(String value1, String value2) {
            addCriterion("chinesePublisher between", value1, value2, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotBetween(String value1, String value2) {
            addCriterion("chinesePublisher not between", value1, value2, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceIsNull() {
            addCriterion("languageDependence is null");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceIsNotNull() {
            addCriterion("languageDependence is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceEqualTo(String value) {
            addCriterion("languageDependence =", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotEqualTo(String value) {
            addCriterion("languageDependence <>", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceGreaterThan(String value) {
            addCriterion("languageDependence >", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceGreaterThanOrEqualTo(String value) {
            addCriterion("languageDependence >=", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceLessThan(String value) {
            addCriterion("languageDependence <", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceLessThanOrEqualTo(String value) {
            addCriterion("languageDependence <=", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceLike(String value) {
            addCriterion("languageDependence like", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotLike(String value) {
            addCriterion("languageDependence not like", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceIn(List<String> values) {
            addCriterion("languageDependence in", values, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotIn(List<String> values) {
            addCriterion("languageDependence not in", values, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceBetween(String value1, String value2) {
            addCriterion("languageDependence between", value1, value2, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotBetween(String value1, String value2) {
            addCriterion("languageDependence not between", value1, value2, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andRatingIsNull() {
            addCriterion("rating is null");
            return (Criteria) this;
        }

        public Criteria andRatingIsNotNull() {
            addCriterion("rating is not null");
            return (Criteria) this;
        }

        public Criteria andRatingEqualTo(String value) {
            addCriterion("rating =", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotEqualTo(String value) {
            addCriterion("rating <>", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThan(String value) {
            addCriterion("rating >", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThanOrEqualTo(String value) {
            addCriterion("rating >=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThan(String value) {
            addCriterion("rating <", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThanOrEqualTo(String value) {
            addCriterion("rating <=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLike(String value) {
            addCriterion("rating like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotLike(String value) {
            addCriterion("rating not like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingIn(List<String> values) {
            addCriterion("rating in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotIn(List<String> values) {
            addCriterion("rating not in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingBetween(String value1, String value2) {
            addCriterion("rating between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotBetween(String value1, String value2) {
            addCriterion("rating not between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andBggRankIsNull() {
            addCriterion("bggRank is null");
            return (Criteria) this;
        }

        public Criteria andBggRankIsNotNull() {
            addCriterion("bggRank is not null");
            return (Criteria) this;
        }

        public Criteria andBggRankEqualTo(String value) {
            addCriterion("bggRank =", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankNotEqualTo(String value) {
            addCriterion("bggRank <>", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankGreaterThan(String value) {
            addCriterion("bggRank >", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankGreaterThanOrEqualTo(String value) {
            addCriterion("bggRank >=", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankLessThan(String value) {
            addCriterion("bggRank <", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankLessThanOrEqualTo(String value) {
            addCriterion("bggRank <=", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankLike(String value) {
            addCriterion("bggRank like", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankNotLike(String value) {
            addCriterion("bggRank not like", value, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankIn(List<String> values) {
            addCriterion("bggRank in", values, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankNotIn(List<String> values) {
            addCriterion("bggRank not in", values, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankBetween(String value1, String value2) {
            addCriterion("bggRank between", value1, value2, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggRankNotBetween(String value1, String value2) {
            addCriterion("bggRank not between", value1, value2, "bggRank");
            return (Criteria) this;
        }

        public Criteria andBggScoreIsNull() {
            addCriterion("bggScore is null");
            return (Criteria) this;
        }

        public Criteria andBggScoreIsNotNull() {
            addCriterion("bggScore is not null");
            return (Criteria) this;
        }

        public Criteria andBggScoreEqualTo(String value) {
            addCriterion("bggScore =", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreNotEqualTo(String value) {
            addCriterion("bggScore <>", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreGreaterThan(String value) {
            addCriterion("bggScore >", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreGreaterThanOrEqualTo(String value) {
            addCriterion("bggScore >=", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreLessThan(String value) {
            addCriterion("bggScore <", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreLessThanOrEqualTo(String value) {
            addCriterion("bggScore <=", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreLike(String value) {
            addCriterion("bggScore like", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreNotLike(String value) {
            addCriterion("bggScore not like", value, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreIn(List<String> values) {
            addCriterion("bggScore in", values, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreNotIn(List<String> values) {
            addCriterion("bggScore not in", values, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreBetween(String value1, String value2) {
            addCriterion("bggScore between", value1, value2, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggScoreNotBetween(String value1, String value2) {
            addCriterion("bggScore not between", value1, value2, "bggScore");
            return (Criteria) this;
        }

        public Criteria andBggLinkIsNull() {
            addCriterion("bggLink is null");
            return (Criteria) this;
        }

        public Criteria andBggLinkIsNotNull() {
            addCriterion("bggLink is not null");
            return (Criteria) this;
        }

        public Criteria andBggLinkEqualTo(String value) {
            addCriterion("bggLink =", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkNotEqualTo(String value) {
            addCriterion("bggLink <>", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkGreaterThan(String value) {
            addCriterion("bggLink >", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkGreaterThanOrEqualTo(String value) {
            addCriterion("bggLink >=", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkLessThan(String value) {
            addCriterion("bggLink <", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkLessThanOrEqualTo(String value) {
            addCriterion("bggLink <=", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkLike(String value) {
            addCriterion("bggLink like", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkNotLike(String value) {
            addCriterion("bggLink not like", value, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkIn(List<String> values) {
            addCriterion("bggLink in", values, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkNotIn(List<String> values) {
            addCriterion("bggLink not in", values, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkBetween(String value1, String value2) {
            addCriterion("bggLink between", value1, value2, "bggLink");
            return (Criteria) this;
        }

        public Criteria andBggLinkNotBetween(String value1, String value2) {
            addCriterion("bggLink not between", value1, value2, "bggLink");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("createdBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("createdBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("createdBy =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("createdBy <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("createdBy >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("createdBy >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("createdBy <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("createdBy <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("createdBy like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("createdBy not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("createdBy in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("createdBy not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("createdBy between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("createdBy not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("createdDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("createdDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("createdDate =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("createdDate <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("createdDate >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdDate >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("createdDate <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("createdDate <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("createdDate in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("createdDate not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("createdDate between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("createdDate not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNull() {
            addCriterion("modifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNotNull() {
            addCriterion("modifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByEqualTo(String value) {
            addCriterion("modifiedBy =", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotEqualTo(String value) {
            addCriterion("modifiedBy <>", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThan(String value) {
            addCriterion("modifiedBy >", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("modifiedBy >=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThan(String value) {
            addCriterion("modifiedBy <", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThanOrEqualTo(String value) {
            addCriterion("modifiedBy <=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLike(String value) {
            addCriterion("modifiedBy like", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotLike(String value) {
            addCriterion("modifiedBy not like", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByIn(List<String> values) {
            addCriterion("modifiedBy in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotIn(List<String> values) {
            addCriterion("modifiedBy not in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByBetween(String value1, String value2) {
            addCriterion("modifiedBy between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotBetween(String value1, String value2) {
            addCriterion("modifiedBy not between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modifiedDate =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modifiedDate <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modifiedDate >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifiedDate >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modifiedDate <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modifiedDate <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modifiedDate in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modifiedDate not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modifiedDate between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modifiedDate not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdIsNull() {
            addCriterion("relatedGameId is null");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdIsNotNull() {
            addCriterion("relatedGameId is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdEqualTo(String value) {
            addCriterion("relatedGameId =", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdNotEqualTo(String value) {
            addCriterion("relatedGameId <>", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdGreaterThan(String value) {
            addCriterion("relatedGameId >", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdGreaterThanOrEqualTo(String value) {
            addCriterion("relatedGameId >=", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdLessThan(String value) {
            addCriterion("relatedGameId <", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdLessThanOrEqualTo(String value) {
            addCriterion("relatedGameId <=", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdLike(String value) {
            addCriterion("relatedGameId like", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdNotLike(String value) {
            addCriterion("relatedGameId not like", value, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdIn(List<String> values) {
            addCriterion("relatedGameId in", values, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdNotIn(List<String> values) {
            addCriterion("relatedGameId not in", values, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdBetween(String value1, String value2) {
            addCriterion("relatedGameId between", value1, value2, "relatedGameId");
            return (Criteria) this;
        }

        public Criteria andRelatedGameIdNotBetween(String value1, String value2) {
            addCriterion("relatedGameId not between", value1, value2, "relatedGameId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gameInfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}