package com.bgp.mgr.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected Integer limitSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public GameInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart = limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public Integer getLimitSize() {
        return limitSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andGameImageIsNull() {
            addCriterion("gameImage is null");
            return (Criteria) this;
        }

        public Criteria andGameImageIsNotNull() {
            addCriterion("gameImage is not null");
            return (Criteria) this;
        }

        public Criteria andGameImageEqualTo(String value) {
            addCriterion("gameImage =", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotEqualTo(String value) {
            addCriterion("gameImage <>", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageGreaterThan(String value) {
            addCriterion("gameImage >", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageGreaterThanOrEqualTo(String value) {
            addCriterion("gameImage >=", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageLessThan(String value) {
            addCriterion("gameImage <", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageLessThanOrEqualTo(String value) {
            addCriterion("gameImage <=", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageLike(String value) {
            addCriterion("gameImage like", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotLike(String value) {
            addCriterion("gameImage not like", value, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageIn(List<String> values) {
            addCriterion("gameImage in", values, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotIn(List<String> values) {
            addCriterion("gameImage not in", values, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageBetween(String value1, String value2) {
            addCriterion("gameImage between", value1, value2, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameImageNotBetween(String value1, String value2) {
            addCriterion("gameImage not between", value1, value2, "gameImage");
            return (Criteria) this;
        }

        public Criteria andGameNameIsNull() {
            addCriterion("gameName is null");
            return (Criteria) this;
        }

        public Criteria andGameNameIsNotNull() {
            addCriterion("gameName is not null");
            return (Criteria) this;
        }

        public Criteria andGameNameEqualTo(String value) {
            addCriterion("gameName =", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotEqualTo(String value) {
            addCriterion("gameName <>", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameGreaterThan(String value) {
            addCriterion("gameName >", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameGreaterThanOrEqualTo(String value) {
            addCriterion("gameName >=", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLessThan(String value) {
            addCriterion("gameName <", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLessThanOrEqualTo(String value) {
            addCriterion("gameName <=", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLike(String value) {
            addCriterion("gameName like", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotLike(String value) {
            addCriterion("gameName not like", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameIn(List<String> values) {
            addCriterion("gameName in", values, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotIn(List<String> values) {
            addCriterion("gameName not in", values, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameBetween(String value1, String value2) {
            addCriterion("gameName between", value1, value2, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotBetween(String value1, String value2) {
            addCriterion("gameName not between", value1, value2, "gameName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(String value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(String value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(String value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(String value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(String value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(String value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLike(String value) {
            addCriterion("duration like", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotLike(String value) {
            addCriterion("duration not like", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<String> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<String> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(String value1, String value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(String value1, String value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberIsNull() {
            addCriterion("peopleNumber is null");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberIsNotNull() {
            addCriterion("peopleNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberEqualTo(String value) {
            addCriterion("peopleNumber =", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberNotEqualTo(String value) {
            addCriterion("peopleNumber <>", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberGreaterThan(String value) {
            addCriterion("peopleNumber >", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberGreaterThanOrEqualTo(String value) {
            addCriterion("peopleNumber >=", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberLessThan(String value) {
            addCriterion("peopleNumber <", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberLessThanOrEqualTo(String value) {
            addCriterion("peopleNumber <=", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberLike(String value) {
            addCriterion("peopleNumber like", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberNotLike(String value) {
            addCriterion("peopleNumber not like", value, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberIn(List<String> values) {
            addCriterion("peopleNumber in", values, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberNotIn(List<String> values) {
            addCriterion("peopleNumber not in", values, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberBetween(String value1, String value2) {
            addCriterion("peopleNumber between", value1, value2, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andPeopleNumberNotBetween(String value1, String value2) {
            addCriterion("peopleNumber not between", value1, value2, "peopleNumber");
            return (Criteria) this;
        }

        public Criteria andRatingIsNull() {
            addCriterion("rating is null");
            return (Criteria) this;
        }

        public Criteria andRatingIsNotNull() {
            addCriterion("rating is not null");
            return (Criteria) this;
        }

        public Criteria andRatingEqualTo(String value) {
            addCriterion("rating =", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotEqualTo(String value) {
            addCriterion("rating <>", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThan(String value) {
            addCriterion("rating >", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThanOrEqualTo(String value) {
            addCriterion("rating >=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThan(String value) {
            addCriterion("rating <", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThanOrEqualTo(String value) {
            addCriterion("rating <=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLike(String value) {
            addCriterion("rating like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotLike(String value) {
            addCriterion("rating not like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingIn(List<String> values) {
            addCriterion("rating in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotIn(List<String> values) {
            addCriterion("rating not in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingBetween(String value1, String value2) {
            addCriterion("rating between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotBetween(String value1, String value2) {
            addCriterion("rating not between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andSevereIsNull() {
            addCriterion("severe is null");
            return (Criteria) this;
        }

        public Criteria andSevereIsNotNull() {
            addCriterion("severe is not null");
            return (Criteria) this;
        }

        public Criteria andSevereEqualTo(String value) {
            addCriterion("severe =", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotEqualTo(String value) {
            addCriterion("severe <>", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereGreaterThan(String value) {
            addCriterion("severe >", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereGreaterThanOrEqualTo(String value) {
            addCriterion("severe >=", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereLessThan(String value) {
            addCriterion("severe <", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereLessThanOrEqualTo(String value) {
            addCriterion("severe <=", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereLike(String value) {
            addCriterion("severe like", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotLike(String value) {
            addCriterion("severe not like", value, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereIn(List<String> values) {
            addCriterion("severe in", values, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotIn(List<String> values) {
            addCriterion("severe not in", values, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereBetween(String value1, String value2) {
            addCriterion("severe between", value1, value2, "severe");
            return (Criteria) this;
        }

        public Criteria andSevereNotBetween(String value1, String value2) {
            addCriterion("severe not between", value1, value2, "severe");
            return (Criteria) this;
        }

        public Criteria andGameTypeIsNull() {
            addCriterion("gameType is null");
            return (Criteria) this;
        }

        public Criteria andGameTypeIsNotNull() {
            addCriterion("gameType is not null");
            return (Criteria) this;
        }

        public Criteria andGameTypeEqualTo(String value) {
            addCriterion("gameType =", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotEqualTo(String value) {
            addCriterion("gameType <>", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeGreaterThan(String value) {
            addCriterion("gameType >", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeGreaterThanOrEqualTo(String value) {
            addCriterion("gameType >=", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeLessThan(String value) {
            addCriterion("gameType <", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeLessThanOrEqualTo(String value) {
            addCriterion("gameType <=", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeLike(String value) {
            addCriterion("gameType like", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotLike(String value) {
            addCriterion("gameType not like", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeIn(List<String> values) {
            addCriterion("gameType in", values, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotIn(List<String> values) {
            addCriterion("gameType not in", values, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeBetween(String value1, String value2) {
            addCriterion("gameType between", value1, value2, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotBetween(String value1, String value2) {
            addCriterion("gameType not between", value1, value2, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionIsNull() {
            addCriterion("gameIntroduction is null");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionIsNotNull() {
            addCriterion("gameIntroduction is not null");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionEqualTo(String value) {
            addCriterion("gameIntroduction =", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotEqualTo(String value) {
            addCriterion("gameIntroduction <>", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionGreaterThan(String value) {
            addCriterion("gameIntroduction >", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("gameIntroduction >=", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionLessThan(String value) {
            addCriterion("gameIntroduction <", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionLessThanOrEqualTo(String value) {
            addCriterion("gameIntroduction <=", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionLike(String value) {
            addCriterion("gameIntroduction like", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotLike(String value) {
            addCriterion("gameIntroduction not like", value, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionIn(List<String> values) {
            addCriterion("gameIntroduction in", values, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotIn(List<String> values) {
            addCriterion("gameIntroduction not in", values, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionBetween(String value1, String value2) {
            addCriterion("gameIntroduction between", value1, value2, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andGameIntroductionNotBetween(String value1, String value2) {
            addCriterion("gameIntroduction not between", value1, value2, "gameIntroduction");
            return (Criteria) this;
        }

        public Criteria andDesignerIsNull() {
            addCriterion("designer is null");
            return (Criteria) this;
        }

        public Criteria andDesignerIsNotNull() {
            addCriterion("designer is not null");
            return (Criteria) this;
        }

        public Criteria andDesignerEqualTo(String value) {
            addCriterion("designer =", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotEqualTo(String value) {
            addCriterion("designer <>", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerGreaterThan(String value) {
            addCriterion("designer >", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerGreaterThanOrEqualTo(String value) {
            addCriterion("designer >=", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLessThan(String value) {
            addCriterion("designer <", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLessThanOrEqualTo(String value) {
            addCriterion("designer <=", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLike(String value) {
            addCriterion("designer like", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotLike(String value) {
            addCriterion("designer not like", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerIn(List<String> values) {
            addCriterion("designer in", values, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotIn(List<String> values) {
            addCriterion("designer not in", values, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerBetween(String value1, String value2) {
            addCriterion("designer between", value1, value2, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotBetween(String value1, String value2) {
            addCriterion("designer not between", value1, value2, "designer");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceIsNull() {
            addCriterion("languageDependence is null");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceIsNotNull() {
            addCriterion("languageDependence is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceEqualTo(String value) {
            addCriterion("languageDependence =", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotEqualTo(String value) {
            addCriterion("languageDependence <>", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceGreaterThan(String value) {
            addCriterion("languageDependence >", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceGreaterThanOrEqualTo(String value) {
            addCriterion("languageDependence >=", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceLessThan(String value) {
            addCriterion("languageDependence <", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceLessThanOrEqualTo(String value) {
            addCriterion("languageDependence <=", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceLike(String value) {
            addCriterion("languageDependence like", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotLike(String value) {
            addCriterion("languageDependence not like", value, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceIn(List<String> values) {
            addCriterion("languageDependence in", values, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotIn(List<String> values) {
            addCriterion("languageDependence not in", values, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceBetween(String value1, String value2) {
            addCriterion("languageDependence between", value1, value2, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andLanguageDependenceNotBetween(String value1, String value2) {
            addCriterion("languageDependence not between", value1, value2, "languageDependence");
            return (Criteria) this;
        }

        public Criteria andArtistIsNull() {
            addCriterion("artist is null");
            return (Criteria) this;
        }

        public Criteria andArtistIsNotNull() {
            addCriterion("artist is not null");
            return (Criteria) this;
        }

        public Criteria andArtistEqualTo(String value) {
            addCriterion("artist =", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotEqualTo(String value) {
            addCriterion("artist <>", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistGreaterThan(String value) {
            addCriterion("artist >", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistGreaterThanOrEqualTo(String value) {
            addCriterion("artist >=", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistLessThan(String value) {
            addCriterion("artist <", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistLessThanOrEqualTo(String value) {
            addCriterion("artist <=", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistLike(String value) {
            addCriterion("artist like", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotLike(String value) {
            addCriterion("artist not like", value, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistIn(List<String> values) {
            addCriterion("artist in", values, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotIn(List<String> values) {
            addCriterion("artist not in", values, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistBetween(String value1, String value2) {
            addCriterion("artist between", value1, value2, "artist");
            return (Criteria) this;
        }

        public Criteria andArtistNotBetween(String value1, String value2) {
            addCriterion("artist not between", value1, value2, "artist");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeIsNull() {
            addCriterion("publishingAge is null");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeIsNotNull() {
            addCriterion("publishingAge is not null");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeEqualTo(String value) {
            addCriterion("publishingAge =", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeNotEqualTo(String value) {
            addCriterion("publishingAge <>", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeGreaterThan(String value) {
            addCriterion("publishingAge >", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeGreaterThanOrEqualTo(String value) {
            addCriterion("publishingAge >=", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeLessThan(String value) {
            addCriterion("publishingAge <", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeLessThanOrEqualTo(String value) {
            addCriterion("publishingAge <=", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeLike(String value) {
            addCriterion("publishingAge like", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeNotLike(String value) {
            addCriterion("publishingAge not like", value, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeIn(List<String> values) {
            addCriterion("publishingAge in", values, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeNotIn(List<String> values) {
            addCriterion("publishingAge not in", values, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeBetween(String value1, String value2) {
            addCriterion("publishingAge between", value1, value2, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublishingAgeNotBetween(String value1, String value2) {
            addCriterion("publishingAge not between", value1, value2, "publishingAge");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNull() {
            addCriterion("publisher is null");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNotNull() {
            addCriterion("publisher is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherEqualTo(String value) {
            addCriterion("publisher =", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotEqualTo(String value) {
            addCriterion("publisher <>", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThan(String value) {
            addCriterion("publisher >", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("publisher >=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThan(String value) {
            addCriterion("publisher <", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThanOrEqualTo(String value) {
            addCriterion("publisher <=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLike(String value) {
            addCriterion("publisher like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotLike(String value) {
            addCriterion("publisher not like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherIn(List<String> values) {
            addCriterion("publisher in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotIn(List<String> values) {
            addCriterion("publisher not in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherBetween(String value1, String value2) {
            addCriterion("publisher between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotBetween(String value1, String value2) {
            addCriterion("publisher not between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherIsNull() {
            addCriterion("chinesePublisher is null");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherIsNotNull() {
            addCriterion("chinesePublisher is not null");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherEqualTo(String value) {
            addCriterion("chinesePublisher =", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotEqualTo(String value) {
            addCriterion("chinesePublisher <>", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherGreaterThan(String value) {
            addCriterion("chinesePublisher >", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherGreaterThanOrEqualTo(String value) {
            addCriterion("chinesePublisher >=", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherLessThan(String value) {
            addCriterion("chinesePublisher <", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherLessThanOrEqualTo(String value) {
            addCriterion("chinesePublisher <=", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherLike(String value) {
            addCriterion("chinesePublisher like", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotLike(String value) {
            addCriterion("chinesePublisher not like", value, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherIn(List<String> values) {
            addCriterion("chinesePublisher in", values, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotIn(List<String> values) {
            addCriterion("chinesePublisher not in", values, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherBetween(String value1, String value2) {
            addCriterion("chinesePublisher between", value1, value2, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andChinesePublisherNotBetween(String value1, String value2) {
            addCriterion("chinesePublisher not between", value1, value2, "chinesePublisher");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modifiedDate =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modifiedDate <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modifiedDate >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifiedDate >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modifiedDate <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modifiedDate <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modifiedDate in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modifiedDate not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modifiedDate between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modifiedDate not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gameInfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gameInfo
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}