package com.bgp.mgr.dao.domain;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.Id
     *
     * @return the value of userInfo.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.Id
     *
     * @param id the value for userInfo.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }
}