package com.bgp.mgr.dao.domain;

public class UserWish {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userWish.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userWish.userId
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userWish.gameId
     *
     * @mbggenerated
     */
    private Long gameId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userWish.id
     *
     * @return the value of userWish.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userWish.id
     *
     * @param id the value for userWish.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userWish.userId
     *
     * @return the value of userWish.userId
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userWish.userId
     *
     * @param userId the value for userWish.userId
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userWish.gameId
     *
     * @return the value of userWish.gameId
     *
     * @mbggenerated
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userWish.gameId
     *
     * @param gameId the value for userWish.gameId
     *
     * @mbggenerated
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }
}