package com.bgp.mgr.dao;

import com.bgp.mgr.dao.domain.AssessInfo;
import com.bgp.mgr.dao.domain.AssessInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    int countByExample(AssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    int deleteByExample(AssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    int insert(AssessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    int insertSelective(AssessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    List<AssessInfo> selectByExample(AssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssessInfo record, @Param("example") AssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssessInfo record, @Param("example") AssessInfoExample example);
}