package com.bgp.mgr.dao;

import com.bgp.mgr.dao.domain.FriendsCircleInfo;
import com.bgp.mgr.dao.domain.FriendsCircleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendsCircleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int countByExample(FriendsCircleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int deleteByExample(FriendsCircleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int insert(FriendsCircleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int insertSelective(FriendsCircleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    List<FriendsCircleInfo> selectByExample(FriendsCircleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    FriendsCircleInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FriendsCircleInfo record, @Param("example") FriendsCircleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FriendsCircleInfo record, @Param("example") FriendsCircleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendsCircleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendsCircleInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendsCircleInfo record);
}