package com.bgp.mgr.dao;

import com.bgp.mgr.dao.domain.ImageInfo;
import com.bgp.mgr.dao.domain.ImageInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int countByExample(ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int deleteByExample(ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int insert(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int insertSelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    List<ImageInfo> selectByExample(ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    ImageInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ImageInfo record, @Param("example") ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ImageInfo record, @Param("example") ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImageInfo record);
}