package com.bgp.mgr.dao;

import com.bgp.mgr.dao.domain.RecordInfo;
import com.bgp.mgr.dao.domain.RecordInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    int countByExample(RecordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    int deleteByExample(RecordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    int insert(RecordInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    int insertSelective(RecordInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    List<RecordInfo> selectByExample(RecordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecordInfo record, @Param("example") RecordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecordInfo record, @Param("example") RecordInfoExample example);
}