package com.bgp.mgr.dao;

import com.bgp.mgr.dao.domain.UserWish;
import com.bgp.mgr.dao.domain.UserWishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int countByExample(UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int deleteByExample(UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int insert(UserWish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int insertSelective(UserWish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    List<UserWish> selectByExample(UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    UserWish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserWish record, @Param("example") UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserWish record, @Param("example") UserWishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserWish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userWish
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserWish record);
}